package pipeline

import (
	"context"
	"fmt"
	"strings"
)

type PRStage struct {
	client GitHubClient
}

func NewPRStage(client GitHubClient) *PRStage {
	return &PRStage{client: client}
}

func (s *PRStage) Name() string { return "pr" }

func (s *PRStage) Run(ctx context.Context, state *PipelineState) (StageResult, error) {
	parts := strings.SplitN(state.Repo.FullName, "/", 2)
	if len(parts) != 2 {
		return StageResult{}, fmt.Errorf("invalid repo name: %s", state.Repo.FullName)
	}
	owner, repo := parts[0], parts[1]

	title := fmt.Sprintf("fix: #%d %s", state.Issue.Number, state.Issue.Title)
	if len(title) > 72 {
		title = title[:72]
	}

	body := fmt.Sprintf("## Summary\n\nAutomated fix for #%d\n\n## Plan\n\n%s\n\n## Cost\n\n$%.4f\n\n---\nGenerated by NeuralForge",
		state.Issue.Number, state.Plan, state.Cost)

	branch := fmt.Sprintf("neuralforge/issue-%d", state.Issue.Number)

	prNumber, prURL, err := s.client.CreatePR(ctx, owner, repo, title, body, branch, state.Repo.DefaultBranch)
	if err != nil {
		return StageResult{}, fmt.Errorf("create PR: %w", err)
	}

	state.PRNumber = prNumber
	state.PRURL = prURL

	return StageResult{
		Status: StatusPassed,
		Output: fmt.Sprintf("PR #%d created: %s", prNumber, prURL),
	}, nil
}
